# Laboratorio 3
### Security Data Science
- Christian Pérez
- Andrei Portales

#### Preprocesamiento

In [1]:
import pandas as pd
import numpy as np
import re
from collections import Counter
from sklearn import feature_extraction, tree, model_selection, metrics
import matplotlib.pyplot as plt
import matplotlib
import seaborn as sns
%matplotlib inline
from yellowbrick.features import Rank2D
from yellowbrick.features import RadViz

In [2]:
df = pd.read_csv('VirusSample.csv')
df.head()

file  \
0  7ff49f2f0912352416b05c010f35f402cc79feed   
1  50cc6c99ec285d0db45dde07d8fdc18d9098c5b6   
2  f77c6bd4aebacd1a01d02e0cb20642ebf2d32929   
3  349c367c5b88fbb6cafae5d7109588d7250e16b5   
4  021f4aa86b520e1d606ab26699c35546bcd00c27   

                                                 api  class  
0         IntersectRect,GetCurrentProcess,GetVersion  Virus  
1  GetCaretBlinkTime,CountClipboardFormats,GetCon...  Virus  
2  VarR8Pow,GetClipboardViewer,GetInputDesktop,Ge...  Virus  
3  SetTraceCallback,CopyAcceleratorTableW,GetProc...  Virus  
4  SHLoadNonloadedIconOverlayIdentifiers,VarUI8Fr...  Virus

In [3]:
df.shape

(9795, 3)

In [4]:
# Preprosesamiento de datos

# Eliminamos las columnas que no nos interesan "file"
df = df.drop(['file'], axis=1)

# Eliminamos las filas que tienen valores nulos
df = df.dropna()

# change to lower case api and class
df['api'] = df['api'].str.lower()



In [5]:
# for every api in each row, we split it by comma and add it to a list
api_list = []
for row in df['api']:
    x = row.split(',')
    for y in x:
        api_list.append(y)

# delete duplicates in api_list
api_list = list(set(api_list))



In [6]:
print(len(api_list))
print(api_list[0])

7964
imagelist_replace


In [7]:
# # create a column for each api and set the value to 1 if the api is present in the row
# for api in api_list:
#     for row in df['api']:
#         x = row.split(',')
#         if api in x:
#             df[api] = 1
#         else:
#             df[api] = 0



In [8]:
# df.head()

In [9]:
for api in api_list:
    df[api] = df["api"].apply(lambda x: 1 if api in x else 0)

C:\Users\Christian\AppData\Local\Temp\ipykernel_8404\193006340.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[api] = df["api"].apply(lambda x: 1 if api in x else 0)
C:\Users\Christian\AppData\Local\Temp\ipykernel_8404\193006340.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df[api] = df["api"].apply(lambda x: 1 if api in x else 0)
C:\Users\Christian\AppData\Local\Temp\ipykernel_8404\193006340.py:2: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, w

In [10]:
df.head()

api  class  \
0         intersectrect,getcurrentprocess,getversion  Virus   
1  getcaretblinktime,countclipboardformats,getcon...  Virus   
2  varr8pow,getclipboardviewer,getinputdesktop,ge...  Virus   
3  settracecallback,copyacceleratortablew,getproc...  Virus   
4  shloadnonloadediconoverlayidentifiers,varui8fr...  Virus   

   imagelist_replace  closespoolfilehandle  mesincrementalhandlereset  _citan  \
0                  0                     0                          0       0   
1                  0                     0                          0       0   
2                  0                     0                          0       0   
3                  0                     0                          0       0   
4                  0                     0                          0       0   

   mmmaplockedpagesspecifycache  pathtoregion  olebuildversion  \
0                             0             0                0   
1                             0             0                0   
2                             0             0                0   
3                             0             0                0   
4                             0             0                0   

   getshortpathnamea  ...  _fseeki64  getuserobjectsecurity  keclearevent  \
0                  0  ...          0                      0             0   
1                  0  ...          0                      0             0   
2                  0  ...          0                      0             0   
3                  0  ...          0                      0             0   
4                  0  ...          0                      0             0   

   midioutclose  checkcolors  dbguiwaitstatechange  shobjectproperties  \
0             0            0                     0                   0   
1             0            0                     0                   0   
2             0            0                     0                   0   
3             0            0                     0                   0   
4             0            0                     0                   0   

   internetqueryoptiona  setnamedsecurityinfow  interlockedpopentryslist  
0                     0                      0                         0  
1                     0                      0                         0  
2                     0                      0                         0  
3                     0                      0                         0  
4                     0                      0                         0  

[5 rows x 7966 columns]

In [11]:
# df = df.drop(['api'], axis=1)

In [12]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [22]:
tv = TfidfVectorizer(use_idf=True, smooth_idf=True, norm=None, tokenizer=lambda x: x.split(','))
tv_matrix = tv.fit_transform(df['api'])
tv_matrix = tv_matrix.toarray()


In [23]:
df2 = pd.DataFrame(np.round(tv_matrix,2), columns=tv.get_feature_names())

c:\Users\Christian\Documents\python_env\data_sciece_env\lib\site-packages\sklearn\utils\deprecation.py:87: FutureWarning: Function get_feature_names is deprecated; get_feature_names is deprecated in 1.0 and will be removed in 1.2. Please use get_feature_names_out instead.
  warnings.warn(msg, category=FutureWarning)


In [24]:
df2.head()

??0?$basic_fstream@gu?$char_traits@g@std@@@std@@qae@pbdh@z  \
0                                                0.0            
1                                                0.0            
2                                                0.0            
3                                                0.0            
4                                                0.0            

   ??0?$basic_ifstream@du?$char_traits@d@std@@@std@@qae@pb_whh@z  \
0                                                0.0               
1                                                0.0               
2                                                0.0               
3                                                0.0               
4                                                0.0               

   ??0?$basic_ios@du?$char_traits@d@std@@@std@@iae@xz  \
0                                                0.0    
1                                                0.0    
2                                                0.0    
3                                                0.0    
4                                                0.0    

   ??0?$basic_ios@du?$char_traits@d@std@@@std@@ieaa@xz  \
0                                                0.0     
1                                                0.0     
2                                                0.0     
3                                                0.0     
4                                                0.0     

   ??0?$basic_istream@du?$char_traits@d@std@@@std@@qae@pav?$basic_streambuf@du?$char_traits@d@std@@@1@_n@z  \
0                                                0.0                                                         
1                                                0.0                                                         
2                                                0.0                                                         
3                                                0.0                                                         
4                                                0.0                                                         

   ??0?$basic_istream@du?$char_traits@d@std@@@std@@qeaa@peav?$basic_streambuf@du?$char_traits@d@std@@@1@_n@z  \
0                                                0.0                                                           
1                                                0.0                                                           
2                                                0.0                                                           
3                                                0.0                                                           
4                                                0.0                                                           

   ??0?$basic_ofstream@du?$char_traits@d@std@@@std@@qae@pb_whh@z  \
0                                                0.0               
1                                                0.0               
2                                                0.0               
3                                                0.0               
4                                                0.0               

   ??0?$basic_ofstream@du?$char_traits@d@std@@@std@@qae@xz  \
0                                                0.0         
1                                                0.0         
2                                                0.0         
3                                                0.0         
4                                                0.0         

   ??0?$basic_ostream@du?$char_traits@d@std@@@std@@qae@pav?$basic_streambuf@du?$char_traits@d@std@@@1@_n@z  \
0                                                0.0                                                         
1                                                0.0                                                         
2                                                0.0             

In [16]:
# modelTF_IDF.head()

In [17]:
# Train model with 70% train and 30% test using Random Forest
# X_train, X_test, y_train, y_test = model_selection.train_test_split(df, df['class'], test_size=0.3, random_state=0)
# clf = tree.DecisionTreeClassifier()
# clf.fit(X_train, y_train)

In [26]:
# Train model with 70% train and 30% test using Random Forest
X_train, X_test, y_train, y_test = model_selection.train_test_split(df2, df['class'], test_size=0.3, random_state=0)
clf = tree.DecisionTreeClassifier()
clf.fit(X_train, y_train)


DecisionTreeClassifier()

In [27]:
y_pred = clf.predict(X_test)


In [30]:
# Validacion cruzada con k = 10
scores = model_selection.cross_val_score(clf, df2, df['class'], cv=10)
print(scores)

c:\Users\Christian\Documents\python_env\data_sciece_env\lib\site-packages\sklearn\model_selection\_split.py:676: UserWarning: The least populated class in y has only 1 members, which is less than n_splits=10.
  warnings.warn(


[0.93571429 0.95       0.9377551  0.9255102  0.91938776 0.93360572
 0.93462717 0.92849847 0.93360572 0.94382022]


In [28]:
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

In [29]:
print('Accuracy: ', accuracy_score(y_test, y_pred))
print('Confusion matrix: ', confusion_matrix(y_test, y_pred))
print('Classification report: ', classification_report(y_test, y_pred))

Accuracy:  0.9373936713167744
Confusion matrix:  [[  49    0    0    0    0    0    0    0   17    0    0]
 [   0    4    0    0    0    0    0    0   27    0    0]
 [   0    0  115    0    0    0    0    0   14    1    1]
 [   0    0    0    0    0    0    0    0    0    1    0]
 [   2    0    0    0    1    0    0    0    7    0    0]
 [   0    0    0    0    0    0    0    0    1    0    1]
 [   0    0    0    0    0    0    0    0    1    0    0]
 [   0    0    0    0    0    0    0    0    0    0    0]
 [   8    1    5    0    0    0    0    0 1814   11   15]
 [   0    0    0    0    0    0    0    1   28  681    1]
 [   0    0    0    0    0    0    0    0   41    0   91]]
Classification report:                precision    recall  f1-score   support

      Adware       0.83      0.74      0.78        66
       Agent       0.80      0.13      0.22        31
    Backdoor       0.96      0.88      0.92       131
       Crypt       0.00      0.00      0.00         1
  Downloader     

c:\Users\Christian\Documents\python_env\data_sciece_env\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Christian\Documents\python_env\data_sciece_env\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\Users\Christian\Documents\python_env\data_sciece_env\lib\site-packages\sklearn\metrics\_classification.py:1318: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modi